name: ai_translator
description: AI Translator powered by llama
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  llama_flutter_android: any
  # 新增：安卓动态权限请求神器
  permission_handler: any

flutter:
  uses-material-design: true
