name: ai_translator
description: AI Translator powered by llama_cpp
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  llama_cpp_dart: any # 换成这个真正的 C++ 桥接插件

flutter:
  uses-material-design: true
